---
ID: "dc0340a4-1dd6-4ba8-bdd4-8b2cd141c6c8"
Parent: "68c367d4-4543-44c3-8567-184a7f593b18"
Template: "68c367d4-4543-44c3-8567-184a7f593b18"
Path: /sitecore/templates/Project/BasicCompany/Page Types/Page/__Standard Values
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r>
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{4ED48317-062F-4465-B9AF-1E636841525B}">
        <r
          id="{AF0D28F1-B659-4392-8FCF-E250DF527FA3}"
          ph="header"
          uid="{5B4893F1-86BA-4ABA-8CB3-1BD6B0D10CB0}" />
        <r
          id="{78BCD6B7-FB7B-4D9D-90D1-78A2C45FCF49}"
          ph="footer"
          uid="{D40CD9A3-CC19-4772-AA17-191F399340C9}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190501T163828Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
          sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "174ebf60-0f18-41be-a64a-432d897b5e8d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
          sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190930T183117Z
