---
ID: "5fe02cd8-bfc8-5ec1-a758-fb2e0b22b271"
Parent: "7121f1f6-2dfd-542a-8efd-d9339ef532ce"
Template: "7121f1f6-2dfd-542a-8efd-d9339ef532ce"
Path: "/sitecore/templates/Project/basiccompany/Styleguide-Layout-Tabs/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210203T190057Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "65f01f29-e91a-4386-961f-218cedcd6153"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210203T190057Z
