---
ID: "9a697d65-723a-47ed-9066-56263dee57ed"
Parent: "c231fbb4-dcdb-4708-99bc-94760f222cc5"
Template: "c231fbb4-dcdb-4708-99bc-94760f222cc5"
Path: /sitecore/templates/Feature/Navigation/_NavigationItem/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "32cff90d-4fdf-4402-a364-21199e88753d"
      Hint: Navigation Title
      Value: $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190307T181004Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e0b09c96-eb34-4ecf-8e60-f0cff0dc5a28"
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190930T183110Z
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
