---
ID: "4dd9ca55-01af-4a83-bd53-c1793da769e4"
Parent: "8fb2c42c-b950-4be3-b1c6-8ba7f11b2ed8"
Template: "8fb2c42c-b950-4be3-b1c6-8ba7f11b2ed8"
Path: /sitecore/templates/Feature/BasicContent/Accordion Item Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{FE549078-8C72-472A-8EA7-51053E0E1D73}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190507T160837Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
          sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "23b1daff-3341-4fdc-9b41-e5d1cda1995a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
          sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190930T183114Z
