---
ID: "377a001c-d558-525b-80f6-cf5eb298bc02"
Parent: "abe88d5b-59e0-5fbd-bb56-b6925f1c8c94"
Template: "abe88d5b-59e0-5fbd-bb56-b6925f1c8c94"
Path: "/sitecore/templates/Project/basiccompany/Styleguide-ComponentParams Rendering Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210203T190058Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "57bd8559-1c70-470e-a454-5300d3107e50"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210203T190058Z
