---
ID: "3b9e1357-182c-5b49-b3d7-8937b4669f57"
Parent: "4317262e-44b5-5392-9c8a-6d090ad0357e"
Template: "4317262e-44b5-5392-9c8a-6d090ad0357e"
Path: "/sitecore/templates/Project/basiccompany/Styleguide-Multilingual/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210203T190057Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e0eaed46-70dd-434b-bae5-3456040eb2d1"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210203T190057Z
